//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASiNet.App.WCP.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASiNet.App.WCP.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Components.
        /// </summary>
        internal static string cm_title_label {
            get {
                return ResourceManager.GetString("cm_title_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author: {0}.
        /// </summary>
        internal static string cmp_all_author_label {
            get {
                return ResourceManager.GetString("cmp_all_author_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show.
        /// </summary>
        internal static string cmp_all_show_button {
            get {
                return ResourceManager.GetString("cmp_all_show_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ASi.
        /// </summary>
        internal static string cmp_default_mouse_author {
            get {
                return ResourceManager.GetString("cmp_default_mouse_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Control your PC-cursor use the joystick!.
        /// </summary>
        internal static string cmp_default_mouse_description {
            get {
                return ResourceManager.GetString("cmp_default_mouse_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mouse joystick.
        /// </summary>
        internal static string cmp_default_mouse_title {
            get {
                return ResourceManager.GetString("cmp_default_mouse_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ASi.
        /// </summary>
        internal static string cmp_default_ruen_keyboard_author {
            get {
                return ResourceManager.GetString("cmp_default_ruen_keyboard_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default QWERTY Ru-En keyboard.
        /// </summary>
        internal static string cmp_default_ruen_keyboard_description {
            get {
                return ResourceManager.GetString("cmp_default_ruen_keyboard_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian QWERTY keyboard.
        /// </summary>
        internal static string cmp_default_ruen_keyboard_title {
            get {
                return ResourceManager.GetString("cmp_default_ruen_keyboard_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address: {0}.
        /// </summary>
        internal static string cn_address_label {
            get {
                return ResourceManager.GetString("cn_address_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect.
        /// </summary>
        internal static string cn_connect_button {
            get {
                return ResourceManager.GetString("cn_connect_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connecting....
        /// </summary>
        internal static string cn_connecting_label {
            get {
                return ResourceManager.GetString("cn_connecting_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection status..
        /// </summary>
        internal static string cn_connection_status_label {
            get {
                return ResourceManager.GetString("cn_connection_status_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnect.
        /// </summary>
        internal static string cn_disconnect_button {
            get {
                return ResourceManager.GetString("cn_disconnect_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect failed!.
        /// </summary>
        internal static string cn_failed_label {
            get {
                return ResourceManager.GetString("cn_failed_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port: {0}.
        /// </summary>
        internal static string cn_port_label {
            get {
                return ResourceManager.GetString("cn_port_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        internal static string cnt_address_entry_ph {
            get {
                return ResourceManager.GetString("cnt_address_entry_ph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto connect.
        /// </summary>
        internal static string cnt_auto_connect_check_box {
            get {
                return ResourceManager.GetString("cnt_auto_connect_check_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection failed!.
        /// </summary>
        internal static string cnt_connect_failed_label {
            get {
                return ResourceManager.GetString("cnt_connect_failed_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue.
        /// </summary>
        internal static string cnt_continue_button {
            get {
                return ResourceManager.GetString("cnt_continue_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorect address, Valid format: 255.255.255.255.
        /// </summary>
        internal static string cnt_incorrect_address_label {
            get {
                return ResourceManager.GetString("cnt_incorrect_address_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorect port, Valid format: 1-65535.
        /// </summary>
        internal static string cnt_incorrect_port_label {
            get {
                return ResourceManager.GetString("cnt_incorrect_port_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port.
        /// </summary>
        internal static string cnt_port_entry_ph {
            get {
                return ResourceManager.GetString("cnt_port_entry_ph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remember the data.
        /// </summary>
        internal static string cnt_remember_data_check_box {
            get {
                return ResourceManager.GetString("cnt_remember_data_check_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address:.
        /// </summary>
        internal static string set_adderss_label {
            get {
                return ResourceManager.GetString("set_adderss_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 192.168.x.x.
        /// </summary>
        internal static string set_addres_entry_ph {
            get {
                return ResourceManager.GetString("set_addres_entry_ph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto connect:.
        /// </summary>
        internal static string set_auto_connect_label {
            get {
                return ResourceManager.GetString("set_auto_connect_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection settings.
        /// </summary>
        internal static string set_connection_settings_label {
            get {
                return ResourceManager.GetString("set_connection_settings_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Horizontal orientation.
        /// </summary>
        internal static string set_horizontation_orientation_label {
            get {
                return ResourceManager.GetString("set_horizontation_orientation_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default: 44544.
        /// </summary>
        internal static string set_port_entry_ph {
            get {
                return ResourceManager.GetString("set_port_entry_ph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port:.
        /// </summary>
        internal static string set_port_label {
            get {
                return ResourceManager.GetString("set_port_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reverse:.
        /// </summary>
        internal static string set_reverse_label {
            get {
                return ResourceManager.GetString("set_reverse_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accept.
        /// </summary>
        internal static string shell_accept_label {
            get {
                return ResourceManager.GetString("shell_accept_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Components.
        /// </summary>
        internal static string shell_components_title {
            get {
                return ResourceManager.GetString("shell_components_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection.
        /// </summary>
        internal static string shell_connection_title {
            get {
                return ResourceManager.GetString("shell_connection_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Macros.
        /// </summary>
        internal static string shell_macros_title {
            get {
                return ResourceManager.GetString("shell_macros_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send.
        /// </summary>
        internal static string shell_send_label {
            get {
                return ResourceManager.GetString("shell_send_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string shell_settings_title {
            get {
                return ResourceManager.GetString("shell_settings_title", resourceCulture);
            }
        }
    }
}
